# -*- coding: utf-8 -*-
"""data_processing_helper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZNhDd00cOuxV39y95sVoGpUq0aUHOBUV

## **Data Feature Engineering Helper Functions and Classes** ##
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils.validation import check_is_fitted
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import StandardScaler

def identify_skewed_features(X, skew_thresh = 1.0):
    '''
    Identify highly skewed numeric features for log transformation.
    X: pd.DataFrame of features
    skew_thresh: absolute skew above this threshold will be log-transformed
    '''

    transform_dict = {}

    for col in X.select_dtypes(include=[np.number]).columns:
        skew_val = X[col].skew()
        transform_dict[col] = 'log' if abs(skew_val) > skew_thresh else 'raw'

    return transform_dict

def apply_transform(series, transform):
    '''
    Apply a log transformation to a pandas series.
    series: panda series
    transform: str of feature transformation as 'raw' or 'log'.
    '''

    X = series.copy()
    shift = 0

    # If values are less than 0, take absolute value with slight shift
    # to prepare for logistic regression.

    if X.min() <= 0:
        shift = abs(X.min()) + 1e-6
    X_shifted = X + shift

    if transform == 'raw':
        return X_shifted
    elif transform == 'log':
        return np.log(X_shifted)
    else:
        raise ValueError(f'Unknown transform: {transform}')

class VIFSelector(BaseEstimator, TransformerMixin):
    '''
    Feature selector based on Variance Inflation Factor (VIF).
    Uses name-based selection to ensure consistency across pipeline.
    '''

    def __init__(self, thresh = 5.0):
        self.thresh = thresh

    def _to_dataframe(self, X):
        if isinstance(X, pd.DataFrame):
            self.feature_names_in_ = list(X.columns)
            return X.copy()

        # Transform numpy array to DataFrame
        elif isinstance(X, np.ndarray):
            if not hasattr(self, "feature_names_in_"):
                self.feature_names_in_ = [f"x{i}" for i in range(X.shape[1])]
            return pd.DataFrame(X, columns=self.feature_names_in_)

        else:
            raise ValueError("X must be a pandas DataFrame or numpy array.")

    def fit(self, X, y=None):
        '''
        Fit the selector to the data, removing variables with high VIF per threshold
        X: DataFrame or numpy array of features
        '''

        X_df = self._to_dataframe(X)
        features = list(X_df.columns)
        X_temp = X_df.copy()

        # Correlation
        corr = np.corrcoef(X_temp.values, rowvar=False)

        # Inverse correlation
        inv_corr = np.linalg.pinv(corr)

        active_features = features.copy()

        while True:

            # VIFs are the diagnoal of the inverse correlation matrix
            vifs = np.diag(inv_corr)
            max_vif = np.max(vifs)

            # Exit while loop if threshold is greater than the largest remaining VIF value.
            if max_vif <= self.thresh:
                break

            # Drop feature with the highest VIF that is greater than threshold
            max_idx = np.argmax(vifs)
            feature_to_drop = active_features[max_idx]

            # Remove feature by name
            active_features.pop(max_idx)

            # Update inverse correlation matrix
            mask = np.ones(inv_corr.shape[0], dtype=bool)
            mask[max_idx] = False

            a = inv_corr[np.ix_(mask, mask)]
            b = inv_corr[mask, max_idx]
            c = inv_corr[max_idx, max_idx]

            inv_corr = a - np.outer(b, b) / c

        # Final selected features (names only)
        self.selected_features_ = active_features

        # Metadata
        self.feature_metadata_ = {
            f: {'dropped_by_vif': f not in self.selected_features_}
            for f in self.feature_names_in_
        }

        return self

    def transform(self, X):
        '''
        Transform the data by selecting only the selected features.
        X: DataFrame or numpy array of features
        '''

        # Check if it is fitted
        check_is_fitted(self, "selected_features_")

        if isinstance(X, pd.DataFrame):
            # Name-based selection
            return X.loc[:, self.selected_features_]

        elif isinstance(X, np.ndarray):
            # Convert to DataFrame for safe selection
            X_df = pd.DataFrame(X, columns=self.feature_names_in_)
            X_selected = X_df.loc[:, self.selected_features_]
            return X_selected

        else:
            raise ValueError("X must be a pandas DataFrame or numpy array.")

    def get_feature_metadata(self):
        '''
        Retrieve feature metadata on whether feature was kept/dropped.
        '''
        return self.feature_metadata_

class SafeTransformer(BaseEstimator, TransformerMixin):
    '''
    Apply predefined feature transformations.
    Store transformation metadata for downstream inspection.
    Return a DataFrame after transform.
    '''

    def __init__(self, feature_transforms = None):
        '''
        feature_transforms: dict mapping feature names to transformation names.
        '''
        self.feature_transforms = feature_transforms

    def fit(self, X, y=None):
        '''
        Fit the transformer to the data.
        X: DataFrame of features
        '''

        X_new = X.copy()

        # Log-transform skewed features if transformation dictionary not provided.
        if self.feature_transforms is None:
            self.transform_dict = identify_skewed_features(X_new)
        else:
            self.transform_dict = {f: t for f, t in self.feature_transforms.items() if f in X_new.columns}

        self.active_transforms_ = self.transform_dict

        # Metadata for all features
        self.feature_metadata_ = {col: {'transformation': self.active_transforms_.get(col, 'raw')}
                                  for col in X_new.columns}

        self.feature_names_in_ = X_new.columns.to_list()

        return self

    def transform(self, X):
        '''
        Apply the transformations to the data.
        X: DataFrame of features
        '''

        X_new = X.copy()

        for feature, transform_name in self.active_transforms_.items():
            X_new[feature] = apply_transform(X_new[feature], transform_name)

        return X_new

    def get_feature_metadata(self):
        '''
        Always return metadata in dict format {feature: {'transformation': str}}
        '''

        metadata = {}

        for f, meta in self.feature_metadata_.items():
            if isinstance(meta, dict):
                metadata[f] = meta
            else:
                # Handle legacy string format
                metadata[f] = {'transformation': meta}

        return metadata

class DataFrameScaler(StandardScaler):
    '''
    StandardScaler that preserves pandas DataFrame structure.
    '''

    def fit(self, X, y=None):
        '''
        Fit the StandardScaler to the dataframe.
        X: DataFrame of features
        '''

        self._is_dataframe_ = isinstance(X, pd.DataFrame)

        if self._is_dataframe_:
            self._columns_ = X.columns
            self._index_ = X.index

        return super().fit(X, y)

    def transform(self, X):
        '''
        Transform the dataframe using StandardScaler.
        X: DataFrame of features
        '''

        check_is_fitted(self, "mean_")
        X_scaled = super().transform(X)

        if isinstance(X, pd.DataFrame):
            # Ensure we use the index of the passed X
            return pd.DataFrame(X_scaled, columns=X.columns, index=X.index)

        return X_scaled

    def fit_transform(self, X, y= None, **fit_params):
        # Override to ensure DataFrame output
        X_scaled = super().fit_transform(X, y)

        if isinstance(X, pd.DataFrame):
            return pd.DataFrame(X_scaled, columns=X.columns, index=X.index)

        return X_scaled