# -*- coding: utf-8 -*-
"""eda_helper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaFw8Ii-f5ocJQFZP69usmZVcfMQ84Oa

## **EDA Helper Functions** ##
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

"""## General grid function"""

def plot_feature_grid(df, plot_func, cols = 4, figsize_per_row = (16, 3),
                      suptitle = None, target = 'target', map_target=True, **kwargs):
    '''
    Plots all features in a grid using the given plot function.
    Collects returned values from each plot_func.
    df: DataFrame
    plot_func: function to plot each feature
    cols: number of columns in the grid
    figsize_per_row: tuple of (width, height) for each row
    suptitle: title for the figure
    target: str of target
    '''

    df_copy = df.copy()
    features = [col for col in df_copy.columns if col != target]
    n_features = len(features)
    rows = int(np.ceil(n_features / cols))

    fig, axes = plt.subplots(rows, cols, figsize = (figsize_per_row[0], rows * figsize_per_row[1]))
    axes = axes.ravel() if n_features > 1 else [axes]

    results = {}

    # Determine if target should be categorical
    is_target_categorical = df_copy[target].dtype in [np.int64, np.float64] and plot_func.__name__ in ['plot_box', 'plot_violin']

    if is_target_categorical:
        # convert to string categories temporarily
        df_copy[target] = df_copy[target].map(lambda x: f'Class {int(x)}')

    for idx, feature in enumerate(features):
        ret = plot_func(df_copy, feature, axes[idx], target = target, **kwargs)
        if ret is not None:
            results[feature] = ret

    # Hide unused axes
    for ax in axes[n_features:]:
        ax.set_visible(False)

    if suptitle:
        plt.suptitle(suptitle, fontsize = 16, y = 1.02)
        fig.tight_layout(rect = [0, 0, 1, 0.95])
    else:
        fig.tight_layout()

    plt.show()

    return pd.DataFrame.from_dict(results, orient='index', columns=['Value']) if results else None

"""## Individual helper **plot func** for general grid plotting, **plot_feature_grid()**.

### Box Plot
"""

def plot_box(df, feature, ax, target = 'target', **kwargs):
    '''
    Plots a box plot.
    df: Dataframe
    feature: str of feature
    ax: Matplotlib axes object
    '''

    sns.boxplot(x = target, y = feature, data = df, ax = ax, **kwargs)
    ax.set_title(feature)

"""### Violin plot"""

def plot_violin(df, feature, ax, target = 'target', **kwargs):
    '''
    Plots a violin plot.
    df: Dataframe
    feature: str of feature
    ax: Matplotlib axes object
    target: str of target
    '''

    sns.violinplot(x=target, y = feature, data = df, ax = ax, inner = 'quartile', **kwargs)
    ax.set_title(feature)

"""### Histogram"""

def plot_hist(df, feature, ax, target = None):
    '''
    Plots a histogram and calculates the skewness of the feature.
    df: DataFrame
    feature: str of feature
    ax: Matplotlib axes object
    '''

    sns.histplot(df[feature], ax = ax)
    ax.set_title(feature)
    skew_val = df[feature].skew()
    ax.text(0.9, 0.85, f'Skew: {skew_val:.2f}', transform = ax.transAxes,
            ha = 'right', fontsize = 11, weight = 'bold')

"""### Box-Tidwell / Linearity check"""

def plot_linearity(df, feature, ax, target = 'target', num_bins = 10):
    '''
    Plots a scatter plot and checks for linearity with Box-Tidwell test.
    df: Dataframe
    feature: str of feature
    ax: Matplotlib axes object
    target: str of target
    num_bins: int of number of bins
    '''

    if feature == target:
        ax.set_visible(False)
        return None
    try:
        X_bt = df[[feature]] + 1e-6
        X_bt[f'{feature}_logX'] = X_bt[feature] * np.log(X_bt[feature])
        X_bt = sm.add_constant(X_bt)
        model_bt = sm.Logit(df[target].astype(int), X_bt).fit(disp=0)
        bt_pval = model_bt.pvalues[f'{feature}_logX']
    except Exception as e:
        print(f'Skipping Box-Tidwell for {feature}: {e}')
        bt_pval = np.nan

    bins = pd.cut(df[feature], bins=num_bins)
    binned_props = df.groupby(bins, observed=False)[target].mean()
    probs = np.clip(binned_props.values, 0.001, 0.999)
    log_odds = np.log(probs / (1 - probs))
    bin_midpoints = [interval.mid for interval in binned_props.index]

    sns.scatterplot(x = bin_midpoints, y = log_odds, ax = ax)
    sns.regplot(x = bin_midpoints, y = log_odds, scatter = False, ax = ax,
                color = 'red', line_kws = {'linestyle':'--'})
    ax.set_title(f'{feature} (BT p = {bt_pval:.4f})')

    return bt_pval

"""### Count Plot"""

def plot_target_distribution(y, **kwargs):
    '''
    Plot the count of the target variable as a categorical variable.
    y: Series of target values (numeric or categorical)
    '''

    # Convert numeric targets to string categories for plotting
    if np.issubdtype(y.dtype, np.number):
        y_plot = y.map(lambda x: f'Class {int(x)}')
    else:
        y_plot = y

    sns.countplot(x = y_plot)
    plt.title('Target Distribution')
    plt.show()

"""### Correlation Clustermap"""

def plot_corr_clustermap(corr_data):
    '''
    Plots a correlation clustermap.
    corr_data: 2D array of correlation values
    '''
    cg = sns.clustermap(corr_data, cmap = 'coolwarm', annot = True, figsize = (20, 24))
    cg.fig.suptitle('Correlation Clustermap', y = 1.02)
    plt.show()