# -*- coding: utf-8 -*-
"""modeling_april.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdAnDaZSfEboGnfR2KuAY8QIJ51kLr4d

## Modeling Helper Functions and Classes ##

### Architecture overview
---------------------
Inference path:

    PreprocessingPipeline
        ↓
    LogisticInferencePipeline(estimator=FirthLogisticModel | MLELogisticModel)
        ↓
    InferenceResult  ← .to_table(), .plot_forest()
        ↓
    BootstrapInference  ← .get_or_summary(), .get_stability_selection(),
                          .build_forest_data()

Classification path:

    PipelineBuilder(models, model_intent)   ← uses PreprocessingPipeline internally
        ↓
    ModelTrainer       ← RandomizedSearchCV per model
        ↓
    CrossValidator     ← F2-optimised thresholds per fold
        ↓
    ModelAnalyzer      ← test metrics, feature table, error analysis
        ↓
    ModelEvaluator     ← orchestrator + disk I/O
        ↓
    ModelVisualizer    ← PR/ROC/CM, SHAP, error plots
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm

import warnings
import logging
import pickle
from abc import ABC, abstractmethod
from copy import deepcopy
from pathlib import Path

import matplotlib.pyplot as plt
import seaborn as sns
import shap

from sklearn.base import clone
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.inspection import permutation_importance

from firthmodels import FirthLogisticRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from scipy.stats import zscore
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, fbeta_score,
    average_precision_score, roc_auc_score, brier_score_loss, log_loss,
    precision_recall_curve, confusion_matrix, ConfusionMatrixDisplay,
    RocCurveDisplay,
)
from sklearn.calibration import calibration_curve
from IPython.display import display

from data_processing import (
    VIFSelector, apply_transform, identify_skewed_features,
    SafeTransformer, DataFrameScaler
)

"""### Helper Functions"""

def compute_ece(y_true, y_prob, n_bins = 10):
    '''
    Calculate the expected calibration error.
    y_true: series of true binary labels
    y_prob: series of predicted probabilities
    n_bins: number of calibration bins
    '''

    # Bins
    bins = np.linspace(0, 1, n_bins + 1)
    bin_ids = np.clip(np.digitize(y_prob, bins) - 1, 0, n_bins - 1)
    counts = np.bincount(bin_ids, minlength = n_bins)
    nonzero = counts > 0

    # Predictions sum and mean
    pred_sum = np.bincount(bin_ids, weights = y_prob, minlength = n_bins)
    pred_mean = np.zeros(n_bins)
    pred_mean[nonzero] = pred_sum[nonzero] / counts[nonzero]

    # Actual sum and mean
    acc_sum = np.bincount(bin_ids, weights = y_true, minlength = n_bins)
    acc_mean = np.zeros(n_bins)
    acc_mean[nonzero] = acc_sum[nonzero] / counts[nonzero]

    return float(np.sum((counts[nonzero] / len(y_prob))
                        * np.abs(pred_mean[nonzero] - acc_mean[nonzero])))


def get_probabilities(pipe, X):
    '''
    Return (target's positive probability, target's negative probability,
    target's probability matrix) from any pipeline.
    Works for predict_proba and decision_function models.
    pipe: sklearn.pipeline.Pipeline
    X: DataFrame of features
    '''

    # Model
    model = pipe.named_steps['model']

    # Transformations are only for linear or distance-based models
    X_model = pipe[:-1].transform(X) if len(pipe.steps) > 1 else X

    # Models with predict_proba
    if hasattr(model, 'predict_proba'):
        probs = model.predict_proba(X_model)
        if probs.shape[1] == 2:
            return probs[:, 1], probs[:, 0], probs
        y_pos = probs.flatten()
        return y_pos, 1 - y_pos, np.column_stack([1 - y_pos, y_pos])

    # If it does not have predict_proba, calculate probability by scaling scores from decision function
    scores = model.decision_function(X_model).reshape(-1, 1)
    y_pos  = MinMaxScaler().fit_transform(scores).flatten()

    return y_pos, 1 - y_pos, np.column_stack([1 - y_pos, y_pos])


def run_baseline(X_train, y_train, X_test, y_test, strategy = 'stratified'):
    '''
    Fit a DummyClassifier and return metric dict.
    X_train: DataFrame of training features
    y_train: series of training labels
    X_test: DataFrame of test features
    y_test: series of test labels
    strategy: str for strategy. Options: 'stratified', 'most_frequent', 'prior', 'uniform', 'constant'
    '''

    # Instatiate and fit classifier
    clf = DummyClassifier(strategy = strategy, random_state = 42)
    clf.fit(X_train, y_train)

    # Classifier predictions and probabilities
    y_pred = clf.predict(X_test)
    y_prob_matrix = clf.predict_proba(X_test)
    y_prob = y_prob_matrix[:, 1]

    return {
        'model': f'Baseline ({strategy})',
        'accuracy': accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred, pos_label=1, zero_division=0),
        'recall': recall_score(y_test, y_pred, pos_label=1),
        'f1': f1_score(y_test, y_pred, pos_label=1, zero_division=0),
        'f2': fbeta_score(y_test, y_pred, beta=2, average = 'binary'),
        'pr_auc': average_precision_score(y_test, y_prob),
        'roc_auc': roc_auc_score(y_test, y_prob),
        'brier_score': brier_score_loss(y_test, y_prob, pos_label=1),
        'log_loss': log_loss(y_test, y_prob_matrix),
        'ece': compute_ece(y_test.values, y_prob),
    }

"""### Preprocessing"""

class PreprocessingPipeline:
    '''
    Thin wrapper around a sklearn Pipeline that handles three optional steps:
        transform → SafeTransformer (log-transform skewed features)
        scale → DataFrameScaler (StandardScaler preserving column names)
        vif → VIFSelector (iterative VIF-based feature removal)

    Used by both the inference path (LogisticInferencePipeline) and the
    classification path (PipelineBuilder).

    When all intent flags are False, the pipeline will passthrough.
    '''

    def __init__(self, intent = None, feature_transforms = None, vif_thresh = 5.0):
        '''
        intent: dict with keys 'transform', 'scale', 'vif'.
                Each value is bool. Missing keys are treated as False.
        feature_transforms : dict or None
            Mapping {feature_name: 'log'|'raw'}.  If None, SafeTransformer
            auto-detects skewed features (skew > 1 → 'log').
        vif_thresh : float of VIF threshold for feature removal.
        '''

        self.intent = intent or {}
        self.feature_transforms = feature_transforms
        self.vif_thresh = vif_thresh

        # Extract steps
        steps = []
        if self.intent.get('transform'):
            steps.append(('transform', SafeTransformer(feature_transforms)))
        if self.intent.get('scale'):
            steps.append(('scaler', DataFrameScaler()))
        if self.intent.get('vif'):
            steps.append(('vif', VIFSelector(thresh=vif_thresh)))

        # An empty Pipeline (no steps) is a valid passthrough in sklearn.
        self._pipeline = Pipeline(steps) if steps else None

        self.feature_metadata = {}
        self.feature_cols = None

    def fit_transform(self, X, y = None):
        '''
        Fit and transform the data.
        X: DataFrame of features
        y: series of labels
        '''

        if self._pipeline is None:
            self._store_metadata(X)
            return X.copy()

        # Retrieve transformation str of features if there is a pipeline
        X_proc = self._pipeline.fit_transform(X, y)
        self._store_metadata(X_proc)

        return X_proc

    def fit(self, X, y = None):
        '''
        Fit the pipeline. Can change later to just fit instead of fit_transform.
        X: DataFrame of features
        y: series of labels
        '''

        if self._pipeline is None:
            return self

        # Fit and transform data via model pipeline with steps
        self.fit_transform(X, y)
        return self

    def transform(self, X):
        '''
        Transform the data.
        X: DataFrame of features
        '''
        if self._pipeline is None:
            return X.copy()

        # Transform data via model pipeline with steps
        return self._pipeline.transform(X)

    def _store_metadata(self, X_proc):
        '''
        Store feature metadata and feature names.
        X_proc: DataFrame of processed features.
        '''

        # Get feature metadata when transform = True
        transformer = (self._pipeline.named_steps.get('transform')
                       if self._pipeline else None)

        if transformer and hasattr(transformer, 'get_feature_metadata'):
            raw = transformer.get_feature_metadata()
            self.feature_metadata = {
                f: (meta.get('transformation', 'raw')
                    if isinstance(meta, dict) else meta)
                for f, meta in raw.items()
            }
        else:
            # No transformations required for tree-based models
            self.feature_metadata = {col: 'raw' for col in X_proc.columns}

        self.feature_cols = list(X_proc.columns)

    def get_feature_metadata(self):
        '''
        Return feature metadata.
        '''
        return self.feature_metadata

    def get_feature_names_out(self):
        '''
        Return feature names.
        '''
        return self.feature_cols

"""### Inference"""

class BaseInferenceModel(ABC):
    '''
    Abstract base for a fitted logistic inference model.
    Subclasses implement fit() and expose coef_, pvalues_, se_, conf_int_.
    '''

    def __init__(self, coef_warn_thresh = 20):
        '''
        coef_warn_thresh : float threshold and warn if any coefficient exceeds this after fitting.
        '''

        self.coef_warn_thresh = coef_warn_thresh

    def _check_model_stability(self):
        '''
        Warn if coefficients are greater than threshold after fitting likely
        due to quasi-separation.
        '''

        coefs = self.coef_.drop('const', errors = 'ignore')
        if np.any(np.abs(coefs) > self.coef_warn_thresh):
            warnings.warn(
                f'Large coefficients detected (>|{self.coef_warn_thresh}|). '
                'Likely quasi-separation.',
                RuntimeWarning
            )

    @abstractmethod
    def fit(self, X, y): ...

    def get_coef(self): return self.coef_
    def get_pvalues(self): return self.pvalues_
    def get_se(self): return self.se_
    def get_conf_int(self): return self.conf_int_
    def get_feature_names(self): return self.coef_.index

class FirthLogisticModel(BaseInferenceModel):
    '''
    Firth's logistic regression via firthmodels.FirthLogisticRegression

    Use when standard MLE diverges due to quasi-complete separation.
    Inference uses the likelihood-ratio test (LRT) by default.
    Profile-likelihood CIs are used for the confidence intervals.
    '''

    def __init__(self, coef_warn_thresh = 20, inference_method = 'lrt', ci_method = 'pl'):
        '''
        coef_warn_thresh: float threshold to warn if any coefficient exceeds this value after fitting
        inference_method: 'lrt' | 'wald' to compute SE and p-values
        ci_method: 'pl' | 'wald' for confidence interval method
        '''

        super().__init__(coef_warn_thresh)
        self.inference_method = inference_method
        self.ci_method = ci_method

    def _check_full_rank(self, X, tol = 1e-10):
        '''
        Check that design matrix is full rank.
        X: DataFrame of features
        tol: float tolerance for singular values
        '''

        _, s, _ = np.linalg.svd(X, full_matrices = False)
        if np.sum(s > tol) < X.shape[1]:
            raise ValueError('Design matrix is rank deficient. Firth requires full rank.')

    def fit(self, X, y):
        '''
        X: DataFrame where features are already preprocessed (transformed, scaled, VIF-filtered)
        y: Series of target labels
        '''

        # Check if design matrix is full rank
        self._check_full_rank(X)

        # Instantiate Firth logistic regression model
        self.model_ = (FirthLogisticRegression(
            max_iter = 1000, max_halfstep = 50, gtol = 1e-3, xtol = 1e-3
            ).fit(X.values, y.values)
            )

        # Coefficients with features first and then intercept
        index = list(X.columns) + ['const']
        coef = np.concatenate([self.model_.coef_.ravel(), [self.model_.intercept_]])
        self.coef_ = pd.Series(coef, index = index)

        # SE and p-values based on inference method
        # penalized maximum likelihood estimation (lrt) or otherwise
        if self.inference_method == 'lrt':
            self.model_.lrt()
            self.se_ = pd.Series(self.model_.lrt_bse_, index = index)
            self.pvalues_ = pd.Series(self.model_.lrt_pvalues_, index = index)
        else:
            self.se_ = pd.Series(self.model_.bse_, index = index)
            self.pvalues_ = pd.Series(self.model_.pvalues_, index = index)

        # Confidence intervals
        ci = self.model_.conf_int(method = self.ci_method)
        self.conf_int_ = pd.DataFrame(
            {'lower': ci[:, 0], 'upper': ci[:, 1]}, index=index
        )

        # Flag features where PL-CI failed
          #lower >= upper indicates optimizer hit its iteration cap which is a characteristic of quasi-separation).
        # These features get NaN OR CIs in the table rather than a misleading zero-width interval.
        self.ci_valid_ = self.conf_int_['lower'] < self.conf_int_['upper']

        # Warn when features have non-valid confidence intervals
        bad = list(self.ci_valid_.index[~self.ci_valid_])
        if bad:
            warnings.warn(
                f'Profile-likelihood CI failed for: {bad}. '
                'CI bounds are equal; quasi-separation likely. '
                'These features are flagged unstable_ci = True in the table.',
                RuntimeWarning
            )

        # Check if coefficients are greater than coefficient threshold
          # if greater than threshold, likely quasi-separation
        self._check_model_stability()

        return self

class MLELogisticModel(BaseInferenceModel):
    '''
    Standard MLE logistic regression via statsmodels.
    Use when separation is not a concern.
    '''

    def fit(self, X, y):
        '''
        X: DataFrame where features are already preprocessed (transformed, scaled, VIF-filtered)
        y: Series of target labels
        '''

        # Add constant and fit logistic regression model
        X_sm = sm.add_constant(X)
        result = sm.Logit(y, X_sm).fit(disp=0)

        # Save model coefficients, standard error, p-values, and confidence interval
        self.coef_ = result.params
        self.se_  = result.bse
        self.pvalues_ = result.pvalues
        ci = result.conf_int()
        ci.columns = ['lower', 'upper']
        self.conf_int_ = ci


        # Check if coefficients are greater than coefficient threshold
          # if greater than threshold, likely quasi-separation
        self._check_model_stability()

        return self

"""### Inference Pipeline"""

class LogisticInferencePipeline:
    '''
    Combine the PreprocessingPipeline with a BaseInferenceModel estimator.

    -Preprocessing is delegated to PreprocessingPipeline, which handles the passthrough case when intent is empty or None.
    -The estimator (FirthLogisticModel / MLELogisticModel) receives the processed DataFrame.
    -After fitting, .get_result() returns an InferenceResult for tabulation and plotting.
    '''

    def __init__(self, estimator, intent = None, feature_transforms = None,
                 vif_thresh = 5.0):
        '''
        estimator: BaseInferenceModel instance (e.g. FirthLogisticModel() or MLELogisticModel())
        intent: dict or None (e.g. {'transform': True, 'scale': True, 'vif': True})
                Pass None or an empty dict for no preprocessing.
        feature_transforms: dict or None
                optional override for per-feature transform names.
        vif_thresh: float for VIF threshold forwarded to PreprocessingPipeline.
        '''

        self.estimator = estimator

        # Instantiate preprocessor
        self.preprocessor = PreprocessingPipeline(
            intent = intent or {},
            feature_transforms = feature_transforms,
            vif_thresh = vif_thresh
        )

        self.feature_metadata = {}
        self.feature_cols = None

    def fit(self, X, y):
        '''
        Fit the pipeline.
        X: DataFrame of features
        y: series of labels
        '''

        # Fit and transform data in preprocessing pipeline
        X_proc = self.preprocessor.fit_transform(X, y)
        self.feature_metadata = self.preprocessor.get_feature_metadata()
        self.feature_cols = self.preprocessor.get_feature_names_out()

        # Convert to DataFrame if VIFSelector returned a plain array
        if not isinstance(X_proc, pd.DataFrame):
            X_proc = pd.DataFrame(X_proc, columns = self.feature_cols,
                                  index = X.index[:len(X_proc)])

        # Fit data post-preprocessing into estimator
        self.estimator.fit(X_proc, y)

        return self

    def get_coef(self):
        '''
        Return fitted coefficients.
        '''
        return self.estimator.get_coef()

    def get_pvalues(self):
        '''
        Return fitted p-values.
        '''
        return self.estimator.get_pvalues()

    def get_se(self):
        '''
        Return fitted standard errors.
        '''
        return self.estimator.get_se()

    def get_conf_int(self):
        '''
        Return fitted confidence intervals.
        '''
        return self.estimator.get_conf_int()

    def get_result(self):
        '''
        Return an InferenceResult ready for .to_table()- create table and
        .plot_forest()- create forest plot.
        '''
        return InferenceResult(
            coef = self.estimator.get_coef(),
            se = self.estimator.get_se(),
            pvalues = self.estimator.get_pvalues(),
            conf_int = self.estimator.get_conf_int(),
            feature_metadata = self.feature_metadata,
        )

class InferenceResult:
    '''
    Hold fitted inference outputs and provide tabulation + plotting.

    All odds ratios (ORs) are per one standard deviation increase in the preprocessed
    feature (log-transformed where applicable, then standardized).
    '''

    def __init__(self, coef, se, pvalues, conf_int, feature_metadata):
        '''
        coef: series of fitted coefficients
        se: series of fitted standard errors
        pvalues: series of fitted p-values
        conf_int: DataFrame of fitted confidence intervals
        '''
        self.coef = coef
        self.se = se
        self.pvalues = pvalues
        self.conf_int = conf_int
        self.feature_metadata = feature_metadata

    def to_table(self):
        '''
        Build inference table (features only, sorted by p-value)

        unstable_ci: True means that the profile-likelihood CI optimizer did not
        converge for that feature (lower == upper or OR is not within the confidence interval).
        OR CI columns are NaN for these rows.
        Interpret the feature's direction (OR > 1 or < 1) but do not report the CI as a reliable interval.
        '''

        feats = [f for f in self.coef.index if f != 'const']
        coef = self.coef[feats]
        se = self.se[feats]
        pval = self.pvalues[feats]
        ci_lo = self.conf_int.loc[feats, 'lower']
        ci_hi = self.conf_int.loc[feats, 'upper']

        # Detect invalid CIs (lower >= upper)
        ci_valid = (
            (ci_lo.values < ci_hi.values) &
            (coef.values >= ci_lo.values) &
            (coef.values <= ci_hi.values)
        )

        # Inference table
        table = (pd.DataFrame({
            'feature': feats,
            'transformation': [self.feature_metadata.get(f, 'raw') for f in feats],
            'coefficient': coef.values,
            'std_error': se.values,
            'z_value': (coef / se).values,
            'p_value': pval.values,
            'OR_per_SD': np.exp(coef.values),

            # Set OR CI to NaN where PL-CI failed so the forest plot does not draw a zero-width error bar
            'ci_lower_OR': np.where(ci_valid, np.exp(ci_lo.values), np.nan),
            'ci_upper_OR': np.where(ci_valid, np.exp(ci_hi.values), np.nan),
            'unstable_ci': ~ci_valid,
        })
        .sort_values('p_value')
        .reset_index(drop=True))

        return table

    def plot_forest(
        self,
        data,
        primary = 'OR_bootstrap',
        primary_lower = 'ci_lower_bootstrap',
        primary_upper = 'ci_upper_bootstrap',
        secondary = 'OR_per_SD',
        secondary_lower = 'ci_lower_OR',
        secondary_upper = 'ci_upper_OR',
        clip_ci = (1e-5, 1e5),
        bootstrap_thresh = 0.8,
        show_significance = True
    ):
        '''
        Forest plot with bootstrap overlay and original-model reference.

        data: DataFrame output of BootstrapInference.build_forest_data().
              Must contain a 'feature' column plus the primary/secondary OR columns.
        primary/primary_lower/primary_upper: str of column with bootstrap OR point estimate and CI bounds.
        secondary/secondary_lower/secondary_upper: str of column with original model OR and CI bounds (plotted as a reference square).
        clip_ci : tuple of x-axis limits on log scale.
        bootstrap_thresh : float threshold for marking a feature as robust (green vs. grey dot).
        show_significance : bool where True values are overlayed with a red circle for p_value < 0.05.
        '''

        data = data.copy().iloc[::-1]   # bottom-to-top ordering

        x_vals = data[primary]
        x_lo = data[primary_lower]
        x_hi = data[primary_upper]
        xerr = [np.maximum(x_vals - x_lo, 0),
                np.maximum(x_hi - x_vals, 0)]

        # Check if CI intervals are ordered correctly
        if (x_vals - x_lo < 0).any() or (x_hi - x_vals < 0).any():
            logging.warning('Some CI bounds inverted. Check bootstrap scaling.')

        fig, ax = plt.subplots(figsize=(9, max(6, len(data) * 0.55)))

        # Primary: bootstrap OR
        ax.errorbar(x_vals, data['feature'], xerr = xerr,
                    fmt = 'o', color = 'black', ecolor = 'gray',
                    capsize = 3, label = 'Bootstrap OR', zorder = 3)

        # Secondary: original model OR
        if secondary in data.columns:
            ref_vals = data[secondary]
            ref_lo = data.get(secondary_lower, ref_vals)
            ref_hi = data.get(secondary_upper, ref_vals)
            ref_err = [np.maximum(ref_vals - ref_lo, 0),
                        np.maximum(ref_hi - ref_vals, 0)]
            ax.errorbar(ref_vals, data['feature'], xerr = ref_err,
                        fmt = 's', color = 'blue', ecolor = 'lightblue',
                        capsize = 3, label = 'Original model OR', zorder = 2)

        # Significance overlay
        if show_significance and 'p_value' in data.columns:
            sig = data['p_value'] < 0.05
            ax.scatter(x_vals[sig], data.loc[sig, 'feature'],
                       color = 'red', s = 60, label = 'p < 0.05', zorder = 4)

        # Bootstrap stability overlay
        if 'selection_frequency' in data.columns:
            robust = data['selection_frequency'] >= bootstrap_thresh
            colors = robust.map({True: 'green', False: 'gray'})
            sizes = 50 + 100 * data['selection_frequency']
            ax.scatter(x_vals, data['feature'],
                       color = colors, s = sizes, alpha = 0.6,
                       label = 'Bootstrap stability', zorder = 5)

        # Off-scale annotations
        off = (x_vals < clip_ci[0]) | (x_vals > clip_ci[1])
        for feat, val in zip(data.loc[off, 'feature'], x_vals[off]):
            x_a = clip_ci[1] * 0.95 if val > clip_ci[1] else clip_ci[0] * 1.05
            ha  = 'right' if val > clip_ci[1] else 'left'
            ax.annotate('Off-scale', xy = (x_a, feat), xytext = (0, 6),
                        textcoords = 'offset points', va = 'bottom', ha = ha,
                        fontsize = 8, color = 'dimgray')

        ax.axvline(1, linestyle='--', color='blue', zorder=1)
        ax.set_xscale('log')
        ax.set_xlim(*clip_ci)
        ax.set_xlabel('Odds Ratio per SD (log scale)')
        ax.set_ylabel('Feature')
        ax.set_title('Forest Plot (Firth) with Bootstrap Stability')
        ax.legend()
        plt.tight_layout()
        plt.show()

"""### Bootstrap Inference"""

class BootstrapInference:
    '''
    Bootstrap resampling over the full LogisticInferencePipeline.

    Each resample independently re-fits the preprocessor (transform, scale,
    VIF) and the estimator, so the resulting ORs reflect the combined
    uncertainty of preprocessing decisions and model estimation.

    Store exp(β)- the OR per SD- directly and compute means and
    quantile CIs on the OR scale.

    Selection frequency = fraction of resamples where a feature survived
    VIF AND had p < alpha.  Features not retained after VIF will not
    appear in the summary (NaN).
    '''

    def __init__(self, base_model, n_bootstrap = 500,
                 bootstrap_thresh = 0.8, random_state = 42):
        '''
        base_model: LogisticInferencePipeline,
                    fitted pipeline whose deepcopy is re-fitted on each resample
        n_bootstrap: int number of bootstrap resamples
        bootstrap_thresh: float for selection-frequency threshold for the 'robust' flag
        random_state: float for reproducibility
        '''
        self.base_model = base_model
        self.n_bootstrap = n_bootstrap
        self.bootstrap_thresh = bootstrap_thresh
        self.random_state = random_state

        # In-memory state
        self._bootstrap_ors = []
        self._bootstrap_pvals = []
        self._n_successful = 0

    def fit(self, X, y):
        '''
        Fit the pipeline for bootstrapping.
        X: DataFrame of features
        y: series of labels
        '''
        rng = np.random.default_rng(self.random_state)
        n = len(X)

        # Initialize list of present features
        self._feature_presence = []

        # Run bootstrapping
        for _ in range(self.n_bootstrap):
            idx  = rng.integers(0, n, n)
            X_rs = X.iloc[idx].reset_index(drop=True)
            y_rs = y.iloc[idx].reset_index(drop=True)

            model = deepcopy(self.base_model)
            try:
                model.fit(X_rs, y_rs)
                coef = model.get_coef().drop('const', errors = 'ignore')
                pval = model.get_pvalues().drop('const', errors = 'ignore')
                self._bootstrap_ors.append(np.exp(coef))
                self._bootstrap_pvals.append(pval)
                self._n_successful += 1
                present = coef.index
                presence_vec = pd.Series(1, index = present)
                self._feature_presence.append(presence_vec)
            except Exception:
                continue

        if self._n_successful == 0:
            raise RuntimeError('All bootstrap iterations failed. '
                               'Check for separation or rank deficiency.')

        # Save bootstrap ORs, p-values, presence
        self._or_df = pd.DataFrame(self._bootstrap_ors)
        self._pval_df = pd.DataFrame(self._bootstrap_pvals)
        self._presence_df = (
            pd.DataFrame(self._feature_presence)
            .reindex(columns = self._or_df.columns)
            .fillna(0)
        )

        return self

    def get_or_summary(self):
        '''
        Point estimates and quantile CIs for bootstrap ORs.
        '''

        s = pd.DataFrame(index = self._or_df.columns)

        or_df_clipped = self._or_df.clip(lower = 1e-10, upper = 1e10)
        log_or_df = np.log(or_df_clipped)

        # Mean on log scale
        s['OR_bootstrap'] = np.exp(log_or_df.mean())

        # CI on log scale
        s['ci_lower_bootstrap'] = np.exp(
            log_or_df.quantile(0.025)
        )
        s['ci_upper_bootstrap'] = np.exp(
            log_or_df.quantile(0.975)
        )

        # Sign consistency where feature exists
        sign = (log_or_df > 0).astype(float)
        sign_consistency = sign.sum() / self._presence_df.sum()
        s['sign_consistency'] = np.maximum(sign_consistency, 1 - sign_consistency)

        return s.sort_values('OR_bootstrap', ascending = False)

    def get_stability_selection(self, alpha=0.05):
        '''
        Fraction of resamples where feature was retained AND significant.
        alpha: float for p-value threshold
        '''

        significant = (self._pval_df < alpha).astype(float)

        # Frequency of significance when present in resample
        freq = significant.sum() / self._presence_df.sum()

        return (pd.DataFrame({'selection_frequency': freq})
                  .sort_values('selection_frequency', ascending = False)
               )

    def get_final_inference(self):
        '''
        Combined OR summary, selection, stability, and robust flag.
        '''

        # Bootstrap OR summary
        summary = self.get_or_summary()

        # Stability
        stability = self.get_stability_selection()

        # Final inference dataframe
        final = summary.join(stability, how = 'outer')
        final['robust'] = (
            (final['selection_frequency'] >= self.bootstrap_thresh) &
            (final['sign_consistency'] >= 0.9)
        )
        final['stability_score'] = final['selection_frequency'] * final['sign_consistency']

        return final.sort_values('stability_score', ascending=False)

    def build_forest_data(self, base_inference_table):
        '''
        Merge bootstrap summary with the base model's inference table.
        The result is passed directly to InferenceResult.plot_forest().

        base_inference_table: DataFrame the output of InferenceResult.to_table().
        '''

        # Retrieve final bootstrap inference dataframe
        summary = self.get_final_inference()

        # Reset index to feature
        summary = (summary.reset_index()
                          .rename(columns = {'index': 'feature'})
        )

        # Merge on feature
        merged = summary.merge(base_inference_table, on = 'feature', how = 'left')

        return merged

    def plot_selection_frequency(self, top_n = None, figsize = (8, 6)):
        '''
        Bar chart of bootstrap selection frequency with threshold line.
        top_n: int for top n features to plot
        '''

        # Reset stability selection dataframe
        df = (self.get_stability_selection()
              .reset_index()
              .rename(columns = {'index': 'feature'}))

        # Plot only top n features
        if top_n:
            df = df.head(top_n)

        plt.figure(figsize = figsize)
        sns.barplot(data = df, y = 'feature', x = 'selection_frequency',
                    palette = 'viridis', hue = 'feature', legend = False)
        plt.axvline(self.bootstrap_thresh, linestyle = '--', color = 'red',
                    label = f'robust ≥ {self.bootstrap_thresh}')

        plt.title('Bootstrap Feature Stability')
        plt.xlabel('Selection Frequency')
        plt.ylabel('Feature')
        plt.legend()
        plt.tight_layout()
        plt.show()

"""### Classification"""

class PipelineBuilder:
    '''
    Build sklearn Pipeline per model according to model_intent.

    For classification, the preprocessing steps (transform / scale / vif)
    are embedded inside a standard sklearn Pipeline so that
    RandomizedSearchCV can clone and refit them.

    Each pipeline has the structure:
        [('transform', SafeTransformer), ('scaler', DataFrameScaler),
         ('vif', VIFSelector), ('model', estimator)]
    where steps are omitted if the corresponding intent flag is False.
    '''

    def __init__(self, models, model_intent, feature_transforms = None,
                 vif_thresh = 5.0):
        '''
        models: dict {model name: estimator}
        model_intent: dict {model name: {'transform': bool, 'scale': bool, 'vif': bool}}
        feature_transforms: dict or None which is forwarded to SafeTransformer.
        vif_thresh: float VIF threshold used in VIFSelector.
        '''

        self.models = models
        self.model_intent = model_intent or {}
        self.feature_transforms = feature_transforms
        self.vif_thresh = vif_thresh

    def build(self):
        '''
        Build model pipeline.
        '''

        pipelines = {}

        for name, model in self.models.items():
            intent = self.model_intent.get(name) or {}

            steps = []
            if intent.get('transform', False):
                steps.append(('transform', SafeTransformer(self.feature_transforms)))
            if intent.get('scale', False):
                steps.append(('scaler', DataFrameScaler()))
            if intent.get('vif', False):
                steps.append(('vif', VIFSelector(thresh=self.vif_thresh)))

            steps.append(('model', model))
            pipelines[name] = Pipeline(steps)

        return pipelines

class ModelTrainer:
    '''
    Fit pipelines, optionally running RandomizedSearchCV for hyperparameter
    tuning where a param_grid is specified.
    '''

    def __init__(self, param_grids = None, cv = None, scoring = 'roc_auc',  n_iter = 20):
        '''
        param_grids: dict of model parameters {model name: {parameter name: parameter,...}}
        cv: sklearn CV splitter
        n_iter: int number for RandomizedSearchCV iterations
        scoring: str for scoring metric of RandomizedSearchCV
        '''

        self.param_grids = param_grids or {}
        self.cv = cv
        self.n_iter = n_iter
        self.scoring = scoring

    def fit(self, pipelines, X, y):
        '''
        Return dict best fitted pipeline {name: best_pipeline}
        '''

        # Best pipeline dictionary
        best = {}

        # Find best hyperparameters per model
        for name, pipe in pipelines.items():

            # Run RandomizedSearchCV if param_grid provided
            if name in self.param_grids:
                search = RandomizedSearchCV(
                    pipe, self.param_grids[name],
                    n_iter = self.n_iter, cv = self.cv,
                    scoring = self.scoring, n_jobs = -1, random_state = 42
                )
                search.fit(X, y)
                best[name] = search.best_estimator_
            else:
                pipe.fit(X, y)
                best[name] = pipe

        return best

class CrossValidator:
    '''
    Run stratified k-fold CV, compute PR-AUC per fold, and find the
    threshold that maximises F2 score using a coarse-to-fine grid search.
    '''

    def __init__(self, cv, coarse_n=50, fine_n=50, zoom_frac=0.1):
        '''
        cv: sklearn CV splitter
        coarse_n, fine_n: int number for grid points in threshold search
        zoom_frac: float half-width around for fine search threshold
        '''

        self.cv = cv
        self.coarse_n = coarse_n
        self.fine_n = fine_n
        self.zoom_frac = zoom_frac

    def evaluate(self, pipelines, X, y):
        '''
        Run cross-validation
        pipelines: dict {model name: Pipeline}
        X: DataFrame of features
        y: series of target labels
        '''

        threshold_info = {}
        rows = []

        for name, pipe in pipelines.items():
            all_thresh, pr_aucs = [], []

            for tr_idx, val_idx in self.cv.split(X, y):
                X_tr, X_val = X.iloc[tr_idx], X.iloc[val_idx]
                y_tr, y_val = y.iloc[tr_idx], y.iloc[val_idx]

                cv_pipe = clone(pipe)
                cv_pipe.fit(X_tr, y_tr)
                y_prob, _, _ = get_probabilities(cv_pipe, X_val)
                pr_aucs.append(average_precision_score(y_val, y_prob))

                # Coarse search
                coarse = np.linspace(0, 1, self.coarse_n)
                f2_c = [fbeta_score(y_val, (y_prob >= t).astype(int), beta=2) for t in coarse]
                best_c = coarse[np.argmax(f2_c)]

                # Fine search
                fine = np.linspace(max(0, best_c - self.zoom_frac / 2),
                                   min(1, best_c + self.zoom_frac / 2),
                                   self.fine_n)
                f2_f = [fbeta_score(y_val, (y_prob >= t).astype(int), beta=2) for t in fine]

                # Append best threshold
                all_thresh.append(fine[np.argmax(f2_f)])

            threshold_info[name] = float(np.mean(all_thresh))
            rows.append({
                'model': name,
                'cv_pr_auc': float(np.mean(pr_aucs)),
                'cv_pr_auc_std': float(np.std(pr_aucs)),
            })

        return pd.DataFrame(rows), threshold_info

class ModelAnalyzer:
    '''
    Evaluate pipelines on the hold-out test set, build feature tables,
    and perform error analysis on the best model.
    '''

    def __init__(self, X_train, y_train, X_test, y_test,
                 best_pipelines, threshold_info, cv_results):
        '''
        X_train: Dataframe of training data
        y_train: series of training labels
        X_test: Dataframe of testing data
        y_test: series of testing labels
        best_pipelines: dict of trained pipelines per model {model_name: Pipeline}
        threshold_info: dict of optimal thresholds from CV {model_name: float}
        cv_results: DataFrame of cross-validation results per model.
        '''

        self.X_train, self.y_train = X_train, y_train
        self.X_test, self.y_test = X_test, y_test
        self.best_pipelines = best_pipelines
        self.threshold_info = threshold_info
        self.cv_results = cv_results

        # Populated by evaluate_test_set()
        self.test_df = None
        self.results_df = None
        self.best_model_name = None
        self.best_model_pipeline = None
        self.best_threshold = None

        # Populated by build_feature_processing_table()
        self.feature_processing_table_ = None

        # Populated by analyze_errors()
        self.error_analysis = None

    # --- Test-set evaluation --------------------------------------------------
    def _compute_metrics(self, y_true, y_pred, y_prob, y_prob_matrix, threshold):
        '''
        Return dictionary of computed metrics from
        y_true: series of actual labels
        y_pred: series of predicted labels
        y_prob: series of predicted probabilities
        y_prob_matrix: array of predicted probabilities
        threshold: float for model threshold
        '''

        return {
            'threshold': threshold,
            'accuracy': accuracy_score(y_true, y_pred),
            'precision': precision_score(y_true, y_pred, pos_label=1, zero_division=0),
            'recall': recall_score(y_true, y_pred, pos_label=1),
            'f1': f1_score(y_true, y_pred, pos_label=1, zero_division=0),
            'f2': fbeta_score(y_true, y_pred, beta=2, average='binary'),
            'pr_auc': average_precision_score(y_true, y_prob),
            'roc_auc': roc_auc_score(y_true, y_prob),
            'brier_score': brier_score_loss(y_true, y_prob, pos_label=1),
            'log_loss': log_loss(y_true, y_prob_matrix),
            'ece': compute_ece(y_true.values, y_prob),
        }

    def evaluate_test_set(self):
        '''
        Compute metrics for all pipelines and identify the best model.
        '''

        # Each row is for each model and its computed metrics (separate columns)
        rows = []
        for name, pipe in self.best_pipelines.items():
            y_prob, _, y_prob_matrix = get_probabilities(pipe, self.X_test)
            threshold = self.threshold_info[name]
            y_pred = (y_prob >= threshold).astype(int)
            metrics = self._compute_metrics(self.y_test, y_pred, y_prob, y_prob_matrix, threshold)
            rows.append({'model': name, **metrics})

        # Convert row metrics into dataframe with CV results
          # Prioritize F2 score
        self.test_df = pd.DataFrame(rows)
        self.results_df = (
            self.test_df
            .merge(self.cv_results, on = 'model', how = 'left')
            .sort_values(['f2', 'recall', 'brier_score'], ascending=[False, False, True])
            .reset_index(drop=True)
        )

        # Best model metrics
        best_row = self.results_df.iloc[0]
        self.best_model_name = best_row['model']
        self.best_model_pipeline = self.best_pipelines[self.best_model_name]
        self.best_threshold = self.threshold_info[self.best_model_name]

        return self.results_df

    # --- Feature table builder ------------------------------------------------
    def build_feature_processing_table(self):
        '''
        Summarize transformations, scaling, VIF, and importance of each feature in each model.
        '''

        rows = []

        for name, pipeline in self.best_pipelines.items():
            model       = pipeline.named_steps['model']
            transformer = pipeline.named_steps.get('transform')
            scaler      = pipeline.named_steps.get('scaler')
            vif_step    = pipeline.named_steps.get('vif')

            all_features = list(self.X_train.columns)
            feature_metadata = {f: {} for f in all_features}

            # Transform metadata
            if transformer and hasattr(transformer, 'get_feature_metadata'):
                for f, meta in transformer.get_feature_metadata().items():
                    feature_metadata[f].update(meta if isinstance(meta, dict) else {'transformation': meta})
            else:
                for f in all_features:
                    feature_metadata[f]['transformation'] = 'raw'

            # Scaling
            for f in all_features:
                feature_metadata[f]['scaled'] = bool(scaler)

            # VIF selection
            if vif_step and hasattr(vif_step, 'selected_features_'):
                selected = set(vif_step.selected_features_)
                final_features = list(vif_step.selected_features_)
                for f in all_features:
                    feature_metadata[f]['dropped_by_vif'] = f not in selected
            else:
                final_features = all_features
                for f in all_features:
                    feature_metadata[f]['dropped_by_vif'] = False

            # Importance
            coef_map, imp_map, perm_map = {}, {}, {}

            # Coefficients
            if hasattr(model, 'coef_'):
                coef_map = dict(zip(final_features, model.coef_.ravel()))

            # Tree-based importance
            if hasattr(model, 'feature_importances_'):
                imp_map = dict(zip(final_features, model.feature_importances_))

            # Permutation importance (ALWAYS compute)
            try:
                r = permutation_importance(
                    pipeline,
                    self.X_test,
                    self.y_test,
                    n_repeats=10,
                    random_state=42,
                    n_jobs=-1
                )
                perm_map = dict(zip(all_features, r.importances_mean))
            except Exception:
                perm_map = {}

            for f in all_features:
                dropped = feature_metadata[f].get('dropped_by_vif', False)

                row = {
                    'model': name,
                    'feature': f,
                    'transformation': feature_metadata[f].get('transformation', 'raw'),
                    'scaled': feature_metadata[f].get('scaled', False),
                    'dropped_by_vif': dropped,

                    # Linear models
                    'coefficient': coef_map.get(f, np.nan),

                    # Tree-based models
                    'importance': imp_map.get(f, np.nan),

                    # Model-agnostic (only if not dropped by VIF)
                    'permutation_importance': (
                        perm_map.get(f, np.nan) if not dropped else np.nan
                    )
                }

                rows.append(row)

            if hasattr(model, 'intercept_'):
                rows.append({
                    'model': name,
                    'feature': '__intercept__',
                    'transformation': None,
                    'scaled': None,
                    'dropped_by_vif': False,
                    'coefficient': float(np.ravel(model.intercept_)[0]),
                    'importance': np.nan,
                    'permutation_importance': np.nan
                })

        self.feature_processing_table_ = pd.DataFrame(rows)
        return self.feature_processing_table_

    def get_final_features(self, model_name):
        '''
        Return list of final features for model.
        model_name: str name of model
        '''

        if self.feature_processing_table_ is None:
            raise RuntimeError('Call build_feature_processing_table() first.')
        df = self.feature_processing_table_.query(
            'model == @model_name and not dropped_by_vif and feature != "__intercept__"'
        )
        return df['feature'].tolist()

    # --- Error analysis -------------------------------------------------------
    def _detect_outliers(self, X, z_thresh = 3.0, iqr_factor = 1.5):
        '''
        Detect outliers.
        X: DataFrame of features
        z_thresh: float for z-score threshold
        iqr_factor: float for IQR threshold
        '''

        # Boolean mask to retrieve if any of the sample's feature values are outside of z-score threshold.
        z_out = (np.abs(zscore(X)) > z_thresh).any(axis=1)

        # Outside of interquartile range
        Q1, Q3 = X.quantile(0.25), X.quantile(0.75)
        IQR = Q3 - Q1
        iqr_out = ((X < Q1 - iqr_factor * IQR) | (X > Q3 + iqr_factor * IQR)).any(axis=1)

        return z_out, iqr_out

    def analyze_errors(self, z_thresh = 3.0, iqr_factor = 1.5, top_n = 10):
        '''
        Build error analysis for the best model.
        z_thresh: float for z-score threshold
        iqr_factor: float for IQR threshold
        top_n: int for # of most confident errors
        '''

        # Extract best model
        pipe = self.best_model_pipeline
        threshold = self.best_threshold
        y_proba, _, _ = get_probabilities(pipe, self.X_test)
        y_pred = (y_proba >= threshold).astype(int)

        df = self.X_test.copy()
        df['y_true'] = self.y_test.values
        df['y_pred'] = y_pred
        df['y_proba'] = y_proba
        df['is_error'] = df['y_true'] != df['y_pred']

        # Determine feature outlier values
        feats = df.drop(columns=['y_true', 'y_pred', 'y_proba', 'is_error'])
        df['zscore_outlier'], df['iqr_outlier'] = self._detect_outliers(feats, z_thresh, iqr_factor)

        confident = (
            df.loc[df['is_error']]
            .assign(confidence = lambda d: np.where(d['y_pred'] == 1, d['y_proba'], 1 - d['y_proba']))
            .sort_values('confidence', ascending = False)
            .head(top_n)
        )

        self.error_analysis = {
            'full_table': df,
            'false_positives': df[(df.y_true == 0) & (df.y_pred == 1)],
            'false_negatives': df[(df.y_true == 1) & (df.y_pred == 0)],
            'confident_errors': confident,
            'summary': (
                df.groupby('is_error')[['zscore_outlier', 'iqr_outlier']]
                .mean()
                .rename(index={False: 'Correct', True: 'Incorrect'})
            )
        }
        return self.error_analysis

    def _rebuild_error_analysis(self, df, top_n=10):
        '''
        Reconstruct error_analysis dict from saved full_table csv.
        df: DataFrame with errors
        top_n: int for # of most confident errors
        '''

        confident = (
            df.loc[df['is_error']]
            .assign(confidence=lambda d: np.where(
                d['y_pred'] == 1, d['y_proba'], 1 - d['y_proba']
            ))
            .sort_values('confidence', ascending=False)
            .head(top_n)
        )

        self.error_analysis = {
            'full_table': df,
            'false_positives': df[(df.y_true == 0) & (df.y_pred == 1)],
            'false_negatives': df[(df.y_true == 1) & (df.y_pred == 0)],
            'confident_errors': confident,
            'summary': (
                df.groupby('is_error')[['zscore_outlier', 'iqr_outlier']]
                .mean()
                .rename(index={False: 'Correct', True: 'Incorrect'})
            )
        }

        return self.error_analysis

class ModelEvaluator:
    '''
    Orchestrator for training, CV, and analysis.
    '''

    def __init__(self, X_train, y_train, X_test, y_test, cv,
                 models, param_grids, model_intent, scoring = 'roc_auc',
                 feature_transforms = None,
                 coarse_n = 50, fine_n = 50, zoom_frac = 0.1,
                 error_top_n = 10,
                 output_dir = Path('model_eval')):
        '''
        X_train: Dataframe of training data
        y_train: series of training labels
        X_test: Dataframe of testing data
        y_test: series of testing labels
        cv: sklearn CV splitter
        models: dict of models
        param_grids: dict of param grids per model
        model_intent: dict of model intent
        feature_transforms: dict of feature transformations
        coarse_n: float for coarse grid search
        fine_n: float for fine grid search
        zoom_frac: float half-width around for fine search threshold
        error_top_n: int # of most confident errors
        output_dir: file path for output
        '''

        self.X_train, self.y_train = X_train, y_train
        self.X_test,  self.y_test  = X_test, y_test
        self.cv = cv
        self.models = models
        self.param_grids = param_grids
        self.model_intent = model_intent
        self.scoring = scoring
        self.feature_transforms = feature_transforms
        self.error_top_n = error_top_n

        self.builder = PipelineBuilder(models, model_intent, feature_transforms)
        self.cv_runner = CrossValidator(cv, coarse_n, fine_n, zoom_frac)

        # In-memory state
        self.best_pipelines = {}
        self.cv_results = None
        self.threshold_info = {}
        self.analyzer = None

        # Disk layout
        self.output_dir = Path(output_dir)
        self.pipeline_dir = self.output_dir / 'pipelines'
        self.cv_file = self.output_dir / 'cv_results.pkl'
        self.thresh_file = self.output_dir / 'thresholds.pkl'
        self.feat_file = self.output_dir / 'feature_table.csv'
        self.error_file = self.output_dir / 'error_analysis.csv'

        for d in [self.output_dir, self.pipeline_dir]:
            d.mkdir(parents=True, exist_ok=True)

        self._load_existing()

    # --- Disk I/O -------------------------------------------------------------
    def _load_existing(self):
        '''
        Load pipelines, CV, thresholds, and reconstruct analyzer if they already exist.
        '''

        for name in self.models:
            p = self.pipeline_dir / f'{name}.pkl'
            if p.exists():
                with open(p, 'rb') as f:
                    self.best_pipelines[name] = pickle.load(f)

        if self.cv_file.exists():
            with open(self.cv_file, 'rb') as f:
                self.cv_results = pickle.load(f)

        if self.thresh_file.exists():
            with open(self.thresh_file, 'rb') as f:
                self.threshold_info = pickle.load(f)

        # Only reconstruct analyzer if pipelines + thresholds exist
        if self.best_pipelines and self.threshold_info:
            self.analyzer = ModelAnalyzer(
                self.X_train, self.y_train,
                self.X_test, self.y_test,
                self.best_pipelines,
                self.threshold_info,
                self.cv_results
            )

            # Load analysis CSVs into analyzer
            if self.feat_file.exists():
                self.analyzer.feature_processing_table_ = pd.read_csv(self.feat_file)

            if self.error_file.exists():
                df = pd.read_csv(self.error_file)
                if not df.empty:
                    self.analyzer.error_analysis = self.analyzer._rebuild_error_analysis(df, top_n = self.error_top_n)

    def _save(self, obj, path, mode='pkl'):
        '''
        Save obj to path.
        obj: object to save
        path: file path
        '''

        path = Path(path)
        if mode == 'pkl':
            with open(path, 'wb') as f:
                pickle.dump(obj, f)
        else:
            obj.to_csv(path, index=False)

    # --- Stage completion checks ----------------------------------------------
    def _pipelines_complete(self):
        '''
        Return True if all pipelines have been trained.
        '''
        return all(name in self.best_pipelines for name in self.models)

    def _cv_complete(self):
        '''
        Return True if CV results have been computed.
        '''
        return (self.cv_results is not None and
                bool(self.threshold_info) and
                all(name in self.threshold_info for name in self.models))

    # --- Run / resume ---------------------------------------------------------
    def run(self):
        '''
        Run all stages of the pipeline.
        '''

        # Run the building of the pipeline
        self._run_stage_1_pipelines()

        # Run cross-validation and threshold optimization
        self._run_stage_2_cv()

        # Run error analysis
        self._run_stage_3_analyze()

        return self.analyzer

    def resume(self):
        '''
        Resume the pipeline.
        '''
        return self.run()

    # --- Stages ---------------------------------------------------------------
    def _run_stage_1_pipelines(self):
        '''
        Run the building of the pipeline.
        '''

        # Check if pipelines have been completed
        if self._pipelines_complete():
            return

        # Build pipelines if they are not missing
        missing = [n for n in self.models if n not in self.best_pipelines]
        models_subset = {n: self.models[n] for n in missing}
        intent_subset = {n: self.model_intent.get(n, {}) for n in missing}
        param_subset = {n: self.param_grids.get(n) for n in missing if n in self.param_grids}

        partial_builder = PipelineBuilder(models_subset, intent_subset, self.feature_transforms)
        pipelines = partial_builder.build()

        # Hyperparameter tuning with RandomizedGridSearch and param subset
        trainer = ModelTrainer(param_subset, self.cv, self.scoring)
        new_pipelines = trainer.fit(pipelines, self.X_train, self.y_train)

        # Save best model with hyperparameters
        for name, pipe in new_pipelines.items():
            self.best_pipelines[name] = pipe
            self._save(pipe, self.pipeline_dir / f'{name}.pkl')

    def _run_stage_2_cv(self):
        '''
        Run cross-validation and threshold optimization.
        '''

        # Check if cross-validation has been completed
        if self._cv_complete():
            return

        # Run cross-validation
        self.cv_results, self.threshold_info = self.cv_runner.evaluate(
            self.best_pipelines, self.X_train, self.y_train
        )

        # Save CV results and threshold information per model
        self._save(self.cv_results, self.cv_file)
        self._save(self.threshold_info, self.thresh_file)

    def _run_stage_3_analyze(self):
        '''
        Run analyzer.
        '''

        if not self.analyzer:
            self.analyzer = ModelAnalyzer(
                self.X_train, self.y_train,
                self.X_test, self.y_test,
                self.best_pipelines,
                self.threshold_info,
                self.cv_results
            )
        self.analyzer.evaluate_test_set()

        # Persist feature table
        if self.analyzer.feature_processing_table_ is None:
            self.analyzer.build_feature_processing_table()
            self._save(self.analyzer.feature_processing_table_, self.feat_file, mode='csv')

        # Persist error analysis
        if self.analyzer.error_analysis is None:
            self.analyzer.analyze_errors()
            self._save(self.analyzer.error_analysis['full_table'], self.error_file, mode='csv')

    def get_final_features(self, model_name):
        '''
        Return list of final features for model.
        model_name: str name of model
        '''

        if self.analyzer is None:
            raise RuntimeError('Call run() first.')

        return self.analyzer.get_final_features(model_name)

    def build_feature_processing_table(self):
        '''
        Build feature processing table.
        '''

        if self.analyzer is None:
            raise RuntimeError('Call run() first.')

        return self.analyzer.build_feature_processing_table()

    def analyze_errors(self):
        '''
        Run error analysis.
        '''

        if self.analyzer is None:
            raise RuntimeError('Call run() first.')

        return self.analyzer.analyze_errors()

class ModelVisualizer:
    '''
    Plot PR/ROC curves, confusion matrices, feature importance, SHAP
    summaries, dependence plots, error distributions, and waterfall charts.
    '''

    def __init__(self, analyzer):
        '''
        analyzer: ModelAnalyzer
        '''
        self.analyzer = analyzer
        self.X_train = analyzer.X_train
        self.y_train = analyzer.y_train
        self.X_test = analyzer.X_test
        self.y_test = analyzer.y_test
        self.test_df = analyzer.test_df
        self.results_df = analyzer.results_df
        self.threshold_info = analyzer.threshold_info
        self.best_pipelines = analyzer.best_pipelines
        self.best_model_pipeline = analyzer.best_model_pipeline
        self.error_analysis = analyzer.error_analysis

    # --- Data Preparation -----------------------------------------------------
    def _transform_features(self, pipeline, X):
        '''
        Apply all preprocessing steps (all steps except 'model').
        pipeline: Pipeline object
        X: DataFrame of features
        '''

        # Tree-based model features do not need feature transformation
        if len(pipeline.steps) <= 1:
            return X

        return pipeline[:-1].transform(X)

    def _get_target_sample(self, name, pipeline, sample_size, random_state,
                           target_sampling):
        '''
        Return target sample (X_transformed_sample, chosen_indices).
        name: str name of model
        pipeline: Pipeline object
        sample_size: int size of sample
        random_state: int seed for random number generator
        target_sampling: str or callable() for type of sample.
              Options: positive, negative, high_error, callable()
        '''

        X_trans = self._transform_features(pipeline, self.X_test)

        cols = self.analyzer.get_final_features(name)

        if X_trans.shape[1] != len(cols):
            # Ensures the DataFrame has correct columns
            X_trans = pd.DataFrame(X_trans, columns=cols, index=self.X_test.index)
        elif not isinstance(X_trans, pd.DataFrame):
            X_trans = pd.DataFrame(X_trans, columns=cols, index=self.X_test.index)

        y_prob, _, _ = get_probabilities(pipeline, self.X_test)

        # Filtering based on target sampling
        if target_sampling == 'positive':
            mask = y_prob >= 0.5
        elif target_sampling == 'negative':
            mask = y_prob < 0.5
        elif target_sampling == 'high_error':
            errors = np.abs(y_prob - self.y_test.values)
            mask   = errors > np.percentile(errors, 75)
        elif callable(target_sampling):
            mask = target_sampling(self.X_test, self.y_test)
        else:
            # Default all rows available
            mask = np.ones(len(X_trans), dtype = bool)

        mask = np.asarray(mask, dtype = bool)
        indices = np.where(mask)[0]
        if len(indices) == 0:
            indices = np.arange(len(X_trans))

        # Randomly selected rows for
        rng = np.random.default_rng(random_state)
        chosen = rng.choice(indices, size = min(sample_size, len(indices)), replace = False)

        return X_trans.iloc[chosen], chosen

    # --- Plots ----------------------------------------------------------------
    def plot_evaluation_metrics(self, name, pipeline):
        '''
        Plot PR curve, ROC curve, and confusion matrix in one row.
        name: str name of model
        pipeline: Pipeline object
        '''

        threshold = self.threshold_info.get(name, 0.5)
        y_prob, _, _ = get_probabilities(pipeline, self.X_test)
        y_pred = (y_prob >= threshold).astype(int)

        fig, axs = plt.subplots(1, 3, figsize=(18, 5))

        prec, rec, _ = precision_recall_curve(self.y_test, y_prob)
        axs[0].plot(rec, prec)
        axs[0].set_title(f'{name} — Precision–Recall')

        RocCurveDisplay.from_predictions(self.y_test, y_prob, ax=axs[1])
        axs[1].set_title(f'{name} — ROC')

        cm = confusion_matrix(self.y_test, y_pred, labels=[1, 0])
        ConfusionMatrixDisplay(cm, display_labels=['Malignant', 'Benign']).plot(
            ax = axs[2], cmap = 'Blues', colorbar = False
        )
        axs[2].set_title(f'{name} — Confusion matrix (thresh={threshold:.2f})')

        plt.tight_layout()
        plt.show()

    # ------------------------------------------------------------------
    def importance_table(self, name, pipeline):
        '''
        Table of important features
        '''

        df = self.analyzer.feature_processing_table_

        # Ensure feature processing table exists
        if df is None:
            df = self.analyzer.build_feature_processing_table()

        df_model = df[(df['model'] == name) & (df['dropped_by_vif'] == False)].copy()

        # Remove intercept
        df_model = df_model[df_model['feature'] != '__intercept__']

        # Drop non-display columns
        df_model = df_model.drop(
            columns=['model', 'scaled', 'dropped_by_vif'],
            errors='ignore'
        )

        # Keep only meaningful importance columns
        importance_cols = ['coefficient', 'importance', 'permutation_importance']
        keep_importance = [
            col for col in importance_cols
            if col in df_model and df_model[col].notna().any()
        ]

        df_model = df_model[['feature', 'transformation'] + keep_importance]

        # Sort by best available metric
        for col in ['permutation_importance', 'importance', 'coefficient']:
            if col in keep_importance:
                df_model = df_model.sort_values(col, key=abs, ascending=False)
                break

        print(f'\n{name} — Important Features\n')
        display(df_model.reset_index(drop=True))

    # ------------------------------------------------------------------
    def plot_shap_analysis(self, name, sample_size = 100, background_size = 50,
                           random_state = 42, target_sampling = None):
        '''
        SHAP bar + beeswarm plots for the names model.
        name: str name of model
        sample_size: int size of sample
        background_size: int size of background
        random_state: int seed for random number generator
        target_sampling: str or callable() for type of sample.
        '''

        pipeline = self.best_pipelines[name]
        model = pipeline.named_steps['model']
        X_sample, _ = self._get_target_sample(
            name, pipeline, sample_size, random_state, target_sampling)
        feature_names = self.analyzer.get_final_features(name)

        if X_sample.shape[1] != len(feature_names):
            logging.warning(f'Feature mismatch for SHAP ({name}). Skipping.')
            return

        X_train_trans = self._transform_features(pipeline, self.X_train)

        if hasattr(model, 'feature_importances_'):
            explainer = shap.TreeExplainer(model)
            shap_values = explainer.shap_values(X_sample)
            if isinstance(shap_values, list):
                shap_values = shap_values[1]

        elif hasattr(model, 'coef_'):
            explainer = shap.LinearExplainer(model, X_train_trans)
            shap_values = explainer.shap_values(X_sample)

        elif hasattr(model, 'decision_function'):
            bg = shap.kmeans(X_train_trans, background_size)
            explainer = shap.KernelExplainer(model.decision_function, bg)
            shap_values = explainer.shap_values(X_sample, nsamples=200)

        else:
            bg = shap.kmeans(X_train_trans, background_size)
            explainer = shap.KernelExplainer(
                lambda x: model.predict_proba(x)[:, 1], bg)
            shap_values = explainer.shap_values(X_sample, nsamples=200)
            if isinstance(shap_values, list):
                shap_values = shap_values[1]

        self.shap_values = shap_values
        self.shap_features = feature_names
        self.shap_sample = X_sample

        # Bar plot
        shap.summary_plot(shap_values, X_sample,
                          feature_names=feature_names, plot_type='bar')

        # Beeswarm plot
        shap.summary_plot(shap_values, X_sample, feature_names=feature_names)

    def plot_shap_dependence(self, feature_name = None, interaction_index = 'auto'):
        '''
        SHAP dependence plot for the top feature (or a named one).
        feature_name: str name of feature
        interaction_index: str or int index of interaction
        '''

        if not hasattr(self, 'shap_values'):
            raise RuntimeError('Run plot_shap_analysis() first.')

        # Specified feature or take the top feature
        if feature_name is None:
            top_idx = int(np.argmax(np.abs(self.shap_values).mean(axis=0)))
            feature_name = self.shap_features[top_idx]

        shap.dependence_plot(
            feature_name, self.shap_values, self.shap_sample,
            feature_names = self.shap_features,
            interaction_index = interaction_index, show = True
        )

    # ------------------------------------------------------------------
    def plot_error_distributions(self, features = None, max_features = 20):
        '''
        KDE plots: correct vs incorrect predictions for each feature.
        features: list of feature names
        max_features: int maximum number of features to plot
        '''

        df = self.error_analysis.get('full_table') if self.error_analysis else None

        if df is None:
            raise RuntimeError('Run analyze_errors() first.')

        if features is None:

            # Get feature processing table
            ft = self.analyzer.feature_processing_table_

            if ft is None:
                raise RuntimeError('Build feature_processing_table first.')

            name = self.analyzer.best_model_name

            # Select features from the model but not the intercept
            features = (
                ft.query('model == @name and feature != "__intercept__"')
                .assign(score = lambda d: d.get(
                    'importance',
                    d.get('coefficient',
                    d.get('permutation_importance',
                          pd.Series(0, index=d.index)))))
                .sort_values('score', ascending=False)
                .head(max_features)['feature'].tolist()
            )

        n = len(features)
        fig, axes = plt.subplots((n + 1) // 2, 2,
                                  figsize=(12, 4 * ((n + 1) // 2)))
        axes = axes.flatten()

        for ax, f in zip(axes, features):
            correct = df.loc[~df['is_error'], f]
            incorrect = df.loc[df['is_error'],  f]
            if len(correct) > 1:
                sns.kdeplot(correct, label='Correct', fill = True, ax = ax)

            if len(incorrect) >= 1:
                if len(incorrect) > 1:
                    sns.kdeplot(
                        incorrect,
                        label='Incorrect',
                        fill=True,
                        ax=ax)

                # For single error, draw a line on plot
                else:
                    ax.axvline(
                        incorrect.iloc[0],
                        color='red',
                        linestyle='--',
                        label='Incorrect')

            ax.set_title(f'{f} — Correct vs Incorrect')
            ax.legend()

        for ax in axes[n:]:
            ax.axis('off')

        plt.tight_layout()
        plt.show()

    def explain_confident_errors_with_shap(self, max_samples = 5):
        '''
        Waterfall SHAP plots for the most confidently wrong predictions.
        max_samples: int maximum number of samples to plot
        '''

        if self.error_analysis is None:
            raise RuntimeError('Run analyze_errors() first.')

        ce = self.error_analysis['confident_errors'].head(max_samples)

        if ce.empty:
            logging.warning('No confident errors found.')
            return

        final_features = self.analyzer.get_final_features(self.analyzer.best_model_name)
        X_err = ce[final_features]

        def pipe_predict(X):
            return self.best_model_pipeline.predict_proba(X)[:, 1]

        explainer = shap.Explainer(pipe_predict, self.X_train)
        shap_values = explainer(X_err)

        for i in range(len(X_err)):
            display(ce.iloc[[i]][['y_true', 'y_pred', 'y_proba']])
            shap.plots.waterfall(shap_values[i], max_display=12)